apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
  name: stackgres
  namespace: stackgres
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8443
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: stackgres
  type: ClusterIP
