apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
  name: tailscale
  namespace: starrocks
spec:
  ports:
    - port: 9030
      protocol: TCP
      targetPort: 9030
  selector:
    app: starrocks
