apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.29.0
    helm.sh/chart: temporal-0.68.1
  name: temporalio-schema-1
  namespace: temporal
spec:
  backoffLimit: 100
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: temporalio
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.29.0
        helm.sh/chart: temporal-0.68.1
      name: temporalio-schema-1
    spec:
      containers:
        - command:
            - sh
            - -c
            - echo "Store setup completed"
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: done
      initContainers:
        - command:
            - sh
            - -c
            - until cqlsh temporalio-cassandra.temporal 9042 -e "SHOW VERSION"; do echo waiting for cassandra to start; sleep 1; done;
          image: cassandra:3.11.3
          imagePullPolicy: IfNotPresent
          name: check-cassandra
        - command:
            - temporal-cassandra-tool
            - create
            - -k
            - temporal
            - --replication-factor
            - "1"
          env:
            - name: CASSANDRA_HOST
              value: temporalio-cassandra.temporal
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-default-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: create-default-store
        - command:
            - temporal-cassandra-tool
            - create
            - -k
            - temporal_visibility
            - --replication-factor
            - "1"
          env:
            - name: CASSANDRA_HOST
              value: temporalio-cassandra.temporal
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal_visibility
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-visibility-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: create-visibility-store
        - command:
            - temporal-cassandra-tool
            - setup-schema
            - -v
            - "0.0"
          env:
            - name: CASSANDRA_HOST
              value: temporalio-cassandra.temporal
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-default-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: setup-default-store
        - command:
            - temporal-cassandra-tool
            - setup-schema
            - -v
            - "0.0"
          env:
            - name: CASSANDRA_HOST
              value: temporalio-cassandra.temporal
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal_visibility
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-visibility-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: setup-visibility-store
        - command:
            - temporal-cassandra-tool
            - update-schema
            - --schema-dir
            - /etc/temporal/schema/cassandra/temporal/versioned
          env:
            - name: CASSANDRA_HOST
              value: temporalio-cassandra.temporal
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-default-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: update-default-store
        - command:
            - temporal-cassandra-tool
            - update-schema
            - --schema-dir
            - /etc/temporal/schema/cassandra/visibility/versioned
          env:
            - name: CASSANDRA_HOST
              value: temporalio-cassandra.temporal
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal_visibility
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-visibility-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: update-visibility-store
      restartPolicy: OnFailure
      serviceAccountName: default
  ttlSecondsAfterFinished: 86400
