apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.29.0
    helm.sh/chart: temporal-0.68.1
  name: temporalio-schema-1
  namespace: temporal
spec:
  backoffLimit: 100
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: temporalio
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.29.0
        helm.sh/chart: temporal-0.68.1
      name: temporalio-schema-1
    spec:
      containers:
        - command:
            - sh
            - -c
            - echo "Store setup completed"
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: done
      initContainers:
        - command:
            - sh
            - -c
            - until curl --silent --fail --user "$ES_USER:$ES_PWD" $ES_SCHEME://$ES_HOST:$ES_PORT 2>&1 > /dev/null; do echo waiting for elasticsearch to start; sleep 1; done;
          env:
            - name: ES_SCHEME
              value: http
            - name: ES_HOST
              value: elasticsearch-master-headless
            - name: ES_PORT
              value: "9200"
            - name: ES_USER
              value: ""
            - name: ES_PWD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-visibility-store
            - name: ES_VERSION
              value: v7
            - name: ES_VISIBILITY_INDEX
              value: temporal_visibility_v1_dev
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: check-elasticsearch
        - command:
            - temporal-sql-tool
            - create-database
          env:
            - name: SQL_PLUGIN
              value: postgres12
            - name: SQL_HOST
              value: mini
            - name: SQL_PORT
              value: "5432"
            - name: SQL_DATABASE
              value: temporal
            - name: SQL_USER
              value: temporal
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-default-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: create-default-store
        - command:
            - temporal-sql-tool
            - setup-schema
            - -v
            - "0.0"
          env:
            - name: SQL_PLUGIN
              value: postgres12
            - name: SQL_HOST
              value: mini
            - name: SQL_PORT
              value: "5432"
            - name: SQL_DATABASE
              value: temporal
            - name: SQL_USER
              value: temporal
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-default-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: setup-default-store
        - args:
            - 'curl -X PUT --fail --user "$ES_USER:$ES_PWD" $ES_SCHEME://$ES_HOST:$ES_PORT/_template/temporal_visibility_v1_template -H "Content-Type: application/json" --data-binary "@schema/elasticsearch/visibility/index_template_$ES_VERSION.json" 2>&1 && curl --head --fail --user "$ES_USER:$ES_PWD" $ES_SCHEME://$ES_HOST:$ES_PORT/$ES_VISIBILITY_INDEX 2>&1 || curl -X PUT --fail --user "$ES_USER:$ES_PWD" $ES_SCHEME://$ES_HOST:$ES_PORT/$ES_VISIBILITY_INDEX 2>&1'
          command:
            - sh
            - -c
          env:
            - name: ES_SCHEME
              value: http
            - name: ES_HOST
              value: elasticsearch-master-headless
            - name: ES_PORT
              value: "9200"
            - name: ES_USER
              value: ""
            - name: ES_PWD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-visibility-store
            - name: ES_VERSION
              value: v7
            - name: ES_VISIBILITY_INDEX
              value: temporal_visibility_v1_dev
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: setup-visibility-store
        - command:
            - temporal-sql-tool
            - update-schema
            - --schema-dir
            - /etc/temporal/schema/postgresql/v12/temporal/versioned
          env:
            - name: SQL_PLUGIN
              value: postgres12
            - name: SQL_HOST
              value: mini
            - name: SQL_PORT
              value: "5432"
            - name: SQL_DATABASE
              value: temporal
            - name: SQL_USER
              value: temporal
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-default-store
          image: temporalio/admin-tools:1.29
          imagePullPolicy: IfNotPresent
          name: update-default-store
      restartPolicy: OnFailure
      serviceAccountName: default
  ttlSecondsAfterFinished: 86400
